# Generated by Django 3.2.9 on 2022-01-11 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0003_alter_studentinfo_regi_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('pay_year', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_month', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('card_num', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('pay_check', models.BooleanField(default=False)),
                ('get_check', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo')),
            ],
        ),
    ]
