# Generated by Django 3.2.9 on 2022-01-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='bank',
            new_name='card_bank',
        ),
        migrations.RenameField(
            model_name='money',
            old_name='card_num',
            new_name='card_number',
        ),
        migrations.RemoveField(
            model_name='money',
            name='pay_month',
        ),
        migrations.RemoveField(
            model_name='money',
            name='pay_year',
        ),
        migrations.AddField(
            model_name='money',
            name='payment_method',
            field=models.CharField(choices=[('cash', '현금결제(영수증X)'), ('crsp', '현금결제(영수증O)'), ('card', '카드결제'), ('zero', '제로페이')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='money',
            name='pay_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
