# Generated by Django 3.2.9 on 2022-01-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20220111_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='get_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
