# Generated by Django 3.2.9 on 2022-01-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_money_get_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='get_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
