# Generated by Django 3.2.9 on 2022-01-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20220112_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='pay_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
