# Generated by Django 3.2.9 on 2022-01-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_money_pay_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='pay_month',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
