# Generated by Django 3.2.9 on 2022-01-11 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211201_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='regi_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
