# Generated by Django 3.2.9 on 2022-01-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentinfo_regi_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='cancel_date',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='card_bank',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='due',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='payment_method',
            field=models.CharField(choices=[('cash', '현금결제(영수증X)'), ('crsp', '현금결제(영수증O)'), ('card', '카드결제'), ('zero', '제로페이')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
