# Generated by Django 3.2.9 on 2022-01-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20220111_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='address',
        ),
    ]
