# Generated by Django 3.2.9 on 2022-01-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_studentinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='payment_method',
            field=models.CharField(choices=[('noty', '미정'), ('cash', '현금결제(영수증X)'), ('crsp', '현금결제(영수증O)'), ('card', '카드결제'), ('zero', '제로페이')], default=None, max_length=50, null=True),
        ),
    ]
