# Generated by Django 3.2.9 on 2022-01-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_studentinfo_sch_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='sch_year',
            field=models.CharField(choices=[('1', '초등학교 1학년'), ('2', '초등학교 2학년'), ('3', '초등학교 3학년'), ('4', '초등학교 4학년'), ('5', '초등학교 5학년'), ('6', '초등학교 6학년'), ('7', '중학교 1학년'), ('8', '중학교 2학년'), ('9', '중학교 3학년'), ('10', '고등학교 1학년'), ('11', '고등학교 2학년'), ('12', '고등학교 3학년')], default=None, max_length=50, null=True),
        ),
    ]
